よくあるテーブルのパターンを追加
kufu/smarthr-patterns pull request #30
Opened 2022-09-02 10:41 UTC by yamish123

## やったこと

よくあるテーブルのパターンを追加
https://smarthr.design/products/design-patterns/smarthr-table/#h3-6

割とボリュームが大きかったので、いくつかのStoryに分けてます

- よくあるテーブル本体（全てのエリアを組み合わせたもの）
- テーブル
- タイトルエリア
- テーブル操作エリア
- 一時操作エリア

## 悩ましポイント

デザインシステム的には、`一時操作エリア` にはテーブルヘッダと、下部の `Pagenation` に分かれているが、コンポーネントを切り出すのが大変だったので、`一時操作エリア` コンポーネントにはテーブルヘッダだけを含める形にした
https://smarthr.design/static/6f451517a9fd44f68b74ee22404248e8/38ca0/smarthr-table-temporary-actionarea.png

↑書いてて思ったけど、`一時操作エリア` コンポーネントに `children` として `Table` を受け取るようにすればできるかも。ただ、そこまでやるかは微妙カモ

2022-09-05 00:40 UTC, uknmr requested changes
何を伝えるかに依ってコンポーネントの切り方が変わりそうですね!
やや複雑になっても、実態に近い方がよさそうかも、と考えました。

2022-09-05 00:40 UTC, uknmr commented on src/patterns/CommonTable/components/Table.tsx
> +  width: 16px;
これマジックナンバーで気になりますね。smarthr-ui 側で吸収した方がいいのかも。

2022-09-05 00:40 UTC, uknmr commented on src/patterns/CommonTable/components/TemporaryOperationArea.tsx
> +                prefix={<FaSearchIcon size={14} alt="検索" color="TEXT_GREY" />}
デフォルト `1em` になるので不要です!

```suggestion
                prefix={<FaSearchIcon alt="検索" color="TEXT_GREY" />}
```

2022-09-05 00:40 UTC, uknmr commented on src/patterns/CommonTable/components/TemporaryOperationArea.tsx
> +const HeaderCluster = styled(Cluster)`
imo

```suggestion
const Wrapper = styled(Cluster)`
```

2022-09-05 00:40 UTC, uknmr commented on src/patterns/CommonTable/components/PageCounter.tsx
> +      letter-spacing: 0.025em;
これの意図気になる。

2022-09-05 00:40 UTC, uknmr commented on src/patterns/CommonTable/components/PageCounter.tsx
> +export const PageCounter: React.FC<Props> = ({ start, end, total }) => (
これ smarthr-ui で提供したい。チケット切っときます!

2022-09-05 00:40 UTC, uknmr commented on src/patterns/CommonTable/components/TableOperationArea.tsx
> +          <Button variant="secondary" prefix={<FaArrowsAltVIcon />}>
imo: Button のデフォルト `secondary` なので明記不要かも

```suggestion
          <Button prefix={<FaArrowsAltVIcon />}>
```

2022-09-06 06:10 UTC, yamish123 reviewed
Story とコンポーネントの作り方難しいですね
あくまでレイアウトサンプルという意味だと、デザインシステムを参照しながら読みやすい形にはなっていると思うのですが、

実際にプロダクトで使う場合は、meyasu で定義している `CommonTable` コンポーネントぐらい扱いやすい形にするとは思うので、そういった書き方もあると良いのかな？
https://github.com/kufu/meyasu/blob/ab038eeb20e325db735989d078418290f35f18c4/client/src/app/components/presentations/blocks/CommonTable/CommonTable.tsx

ただ、↑の実装は可読性はちょっと微妙な気がしているので、うまいこと簡略化したいなという気持ちもあり

2022-09-06 06:10 UTC, yamish123 commented on src/patterns/CommonTable/components/PageCounter.tsx
> +export const PageCounter: React.FC<Props> = ({ start, end, total }) => (
あざます！
smarthr-ui に輸入したいやつはTODOコメント追記しておくようにしました

2022-09-06 06:10 UTC, yamish123 commented on src/patterns/CommonTable/components/PageCounter.tsx
> +      letter-spacing: 0.025em;
meyasu から直接コピペしたものなのでちょっと意図はわからないんですが、
smarthr-ui 側で定義する際に必要に応じてリファクタすればいいかなと思いました！

2022-09-06 06:10 UTC, yamish123 commented on src/patterns/CommonTable/components/Table.tsx
> +  width: 16px;
こちらもTODOコメント追記しつつ、
`<Th checkbox />`
的な感じで、smarhtr-ui 側で指定できるようになると良さそう？

2022-09-06 06:10 UTC, yamish123 commented on src/patterns/CommonTable/components/TableOperationArea.tsx
> +          <Button variant="secondary" prefix={<FaArrowsAltVIcon />}>
消しました！

2022-09-06 06:11 UTC, yamish123 commented on src/patterns/CommonTable/components/TemporaryOperationArea.tsx
> +                prefix={<FaSearchIcon size={14} alt="検索" color="TEXT_GREY" />}
消しました！

2022-09-08 03:23 UTC, uknmr approved these changes
> meyasu で定義している CommonTable コンポーネントぐらい扱いやすい形にするとは思うので、そういった書き方もあると良いのかな？

一旦は Doc にリンクがいい気がしました!

> うまいこと簡略化したい

これもしたい!
できそうな気もするので、おいおいやろうという気持ちになりました!!

2022-09-08 05:54 UTC, yamish123 commented on src/patterns/CommonTable/CommonTable.tsx
> +const Center = styled.div`
EveryLayout にもあった気がするのでほしいですね！ありがとうございます！

2022-09-08 05:54 UTC, yamish123 commented on src/patterns/CommonTable/components/Table.tsx
> +const EmptyCell = styled(Td)`
これも出せると良さそうですね！あざます！

2022-09-08 05:54 UTC, merged