削除ダイアログと取り消しダイアログのStory追加
kufu/smarthr-patterns pull request #9
Opened 2022-08-16 03:32 UTC by yamish123

Storyを開いた状態でdocsタブに移動すると、ダイアログが開いたままになる問題があるんですが、
docsの改善タスクで別途やるので、一旦ここではStoryの追加だけ見てもらえればと〜

2022-08-16 06:27 UTC, uknmr requested changes
使い方の別パターンとして「取り消しダイアログ」があるので、削除ダイアログの中に取り消しダイアログがある構成でもいいかも、と思いました!
別パターン? 同じでは? となりそう。

2022-08-16 06:27 UTC, uknmr commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +    padding: ${spacing.M};
[余白のパターン](https://smarthr.design/products/design-patterns/spacing-layout-pattern/#h3-2) に則り 24px でお願いします!
また、16px の世界線だとTシャツサイズで表現できない余白がでてくる（12pxとか）ので、`space()` の利用を推奨したいです!

```suggestion
  ${({ theme: { space } }) => css`
    padding: ${space(1.5)};
```

2022-08-16 06:27 UTC, uknmr commented on src/patterns/Dialog/CancelDialog/CancelDialog.stories.tsx
> +    <>
Fragment 不要そうに見えるんですが、意図があれば知りたいです!

2022-08-16 06:27 UTC, uknmr commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +    padding: ${spacing.M};
というか、DialogBody の余白決まってるなら smarthr-ui で指定しろよ感ある（やろうやろうと思ってやってないやつ

2022-08-16 06:27 UTC, uknmr commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +      inlineStories: false,
必要そう?

2022-08-16 07:20 UTC, yamish123 commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +    padding: ${spacing.M};
>というか、DialogBody の余白決まってるなら smarthr-ui で指定しろよ感ある（やろうやろうと思ってやってないやつ

これは確かに〜と思いつつ、一旦`space(1.5)`で対応しました！

2022-08-16 07:20 UTC, yamish123 commented on src/patterns/Dialog/CancelDialog/CancelDialog.stories.tsx
> +    <>
意図がない消し忘れだったので消しました！

2022-08-16 07:21 UTC, yamish123 commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +      inlineStories: false,
これがないとdocsを開いたときに画面全体にダイアログのモーダルがかかっちゃうので入れてます
もっと良い解決方法はありそうではあるんですが、docs改善側のタスクでこの辺は修正しようと思ってます〜

2022-08-16 07:21 UTC, yamish123 commented
@uknmr 
もろもろ指摘点修正しました！

2022-08-16 07:23 UTC, uknmr commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +    padding: ${spacing.M};
:arigatau:

2022-08-16 07:23 UTC, uknmr commented on src/patterns/Dialog/DeleteDialog/DeleteDialog.stories.tsx
> +      inlineStories: false,
完全理解!!

2022-08-16 07:24 UTC, uknmr approved these changes
LGTM!

2022-08-16 07:27 UTC, uknmr commented
あ! 取り消しダイアログを削除ダイアログの中に入れてしまう構成についてはどうですか? @yamish123 
https://github.com/kufu/smarthr-patterns/pull/9#pullrequestreview-1073538432

2022-08-16 07:28 UTC, yamish123 commented
あ、見逃してました！

2022-08-16 07:28 UTC, yamish123 commented
削除ダイアログの1Storyとして取り消しダイアログを入れる形にしますね

2022-08-16 07:54 UTC, yamish123 commented
取り消しダイアログを削除ダイアログの中に入れつつ、コンポーネントの構成を整理して`オブジェクト名` などの文言を Story 上から渡せるようにしました！
[3c99a75](https://github.com/kufu/smarthr-patterns/pull/9/commits/3c99a758b0f01133ae1aefe6d94c7e3e015c85dd)

2022-08-16 08:07 UTC, uknmr reviewed
> オブジェクト名 などの文言を Story 上から渡せるようにしました

よさそう!
コンポーネントの I/F にはしたくないけど、変数化したい、みたいなやつをどうしようかと思ってたのでこれパクります!

2022-08-16 08:07 UTC, uknmr commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +          )}
細かいんですがｗ
一番好ましい形で書けるといいな、と思うんですが、実プロダクトでも行ごとに変数チェックして出し分けしない気がしています!
特定のオブジェクトがあるかどうかで `hasEffects` 的な判定して、内側はまとめて書く気がする。

2022-08-16 08:14 UTC, yamish123 commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +          )}
ああ〜〜実プロダクトでコンポーネント使い回すこと考えるとそれはそうですね！
ちょっと見ます！

2022-08-16 08:27 UTC, yamish123 commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +          )}
実プロダクトだとどうするんだろう？
meyasu だと `DeleteDialog` みたいなコンポーネントにはしていないのでどのみちベタ書きで作るので、ここも変に変数で渡さず、ベタ書きのStoryで書いちゃっていいですかね？

```
```

2022-08-16 08:29 UTC, yamish123 commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +          )}
今回実装した形式だと、以下のように使えるけどまあ微妙なのかな〜
```tsx
<DeleteDialog
  objectName="サーベイ"
  objectInstanceName={questionnaire.title} // ex: エンゲージメントサーベイ
  childObjectName="分析など"
/>
```

2022-08-16 09:06 UTC, uknmr commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +          )}
> ベタ書きのStoryで書いちゃっていい

パッと思いついたのは、こんな感じの定義をしちゃって、`const hasRelatedObjects = !!relatedObject.name` みたいな判定をしちゃうやつ。

```
const relatedObject = {
  name: 'hoge',
  instanceName: 'fuga',
  children: [
    { name: 'puyo' }
  ]
}
```


> ここまでやるかと言うと微妙

そう思います!

2022-08-16 09:36 UTC, yamish123 commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +          )}
必要以上に複雑化しちゃったので、一旦ベタ書きのDialogを3種類用意する形にしました〜
[Dialogの内容をベタ書きに変更](https://github.com/kufu/smarthr-patterns/pull/9/commits/c57e0789cc8be9d72040a0be15b5c4fe91ef3e3d)

2022-08-16 11:20 UTC, uknmr reviewed
バラすのよさそう。
また細かいんですが英語が気になってしまった:pray:
effect は影響を受けた結果や効果、みたいな印象があるので influence を提案しました（正しいかどうかはわからない）。

2022-08-17 01:05 UTC, yamish123 commented on src/patterns/DeleteDialog/DeleteDialog.stories.tsx
> +  if (hasEffect) return <DeleteWithEffectsDialog isOpen={isOpen} handleAction={handleAction} handleClose={handleClose} />
対応しました〜！

2022-08-17 01:24 UTC, uknmr approved these changes
LGTM:tada:

2022-08-17 01:24 UTC, merged